### ISSUE TITLE
piplaystate.py crashes with token error

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#13]
I did a fresh install with the new version, but piplaystate.py crashes with the following output:

pi@BAD-HORSE ~/hasystem $ python piplaystate.py
Doing a session check.
Traceback (most recent call last):
  File "piplaystate.py", line 132, in <module>
    state = sessionstatus()
  File "piplaystate.py", line 83, in sessionstatus
    plexlogin()
  File "piplaystate.py", line 49, in plexlogin
    PLEXTOKEN = PLEXTOKEN[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

I'm not sure if this is a bug or just something I'm missing

**Comment by amazingr4b** [comment]
Good catch. A new file is posted that should fix that, assuming you ran the system_setup script and it previously prompted you for the token.

**Comment by MoeFwacky** [comment]
That fixed it, but now it occasionally hangs with this:

**Comment by MoeFwacky** [comment]
I figured out what the recent issue is and it's a separate bug, so I'm going to open a new issue for it.

**Comment by amazingr4b** [comment]
Currently there is no validation when you add a specific preroll or commercial to verify it matches an item that exists, so if you have some error in the name it will throw a title not found error when it tries to then play it. That failure can prevent the playcheck mechanism from getting turned back on, since the error stops the script before the action to restart it. I have plans to add validations for custom preroll/commercial adds in the future that will prevent that from happening, but its something to keep in mind for the time being. I like to use the "listcommercials" action so I can easily copy and paste names to prevent typo errors.  
Running the most recent update file will remove any items that have been removed, and update those that have been updated in plex.  
I am closing this one since the token error issue has been corrected.
