### ISSUE TITLE
[Feature Request] - Do not advance block until x% of the current show has played

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#22]
This is sort of a feature request to work around a bug that I believe is more with the Plex Server or (more likely) RasPlex. 

Sometimes, while in block mode, a show will start playing, and suddenly stop, kicking back to the menu screen and shortly thereafter the script kicks in and starts the next show on the block. What I'm proposing here is a check on the progress of the episode that prevents the block from advancing to the next show, and the show from advancing to the next episode if less than a specified percentage of the episode has played. 

My hope here is that if an episode starts and fails within a few minutes, it would then start again (and resume maybe?) instead of skipping the show entirely.

**Comment by amazingr4b** [comment]
Sounds like a server or network issue. Those can be tricky. As far as your request, this one is not likely to happen unless it becomes a widespread plex problem that they never fix. There are currently no plans to add a mechanism to monitor playback position to the playstate checking script since the server already does that, and that information can be queried when the need to resume something arises. 

The following commands may prove useful in this situation:
seriesskipback "show" --> decreases the shows episode position by 1
resumeplay "title" --> resumes the item from where it last played
setresumestatus on/off --> enables/disables automatic resume from last position instead of start for a title.
