### ISSUE TITLE
[Feature Request] - Show scheduling

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#23]
I'll admit that this one may be a tall order, but I figured I'd give it a shot.

What I would like is a method to schedule certain shows to play at certain times. Perhaps also give each show a preemptive priority to determine what to do if a something else is playing at the scheduled time (either a double episode of a previous show or a movie that ran long). A scheduled show would either start right away, start after the previous item ends or not play at all.

As you know, currently when a block ends, the script kicks into normal mode and plays that way. With scheduled shows though, there should be an option to have only commercials and preroll play until the next scheduled item. So if two shows are scheduled 30 minutes apart, and the first show ends at 22 minutes, it would fill the 8 minute gap with commercials and/or preroll. Bonus if it also picks those files based on length to best fit the time gap without running over or under.

Again, I know this is probably a tall order, and that a lot of this could be accomplished with more creative use of crontab and more blocks containing less shows each. In my current setup, I run a block for every 3 hours of programming, but it's a little clunky, and shows can be knocked off schedule by a number of occurrences. It would be nice to have a more built-in scheduling system to better simulate the feel of a broadcast station.

**Comment by amazingr4b** [comment]
I plan on adding a schedule script that will use cron so that it will be easier to automate changing to various playmodes once I finish my current project to limit the reliance on the tbn database. Some of what you are asking will make the cut, like picking a time/day to automatically change play mode, but other stuff, like automatically filling gaps with commercials probably wont.

**Comment by amazingr4b** [comment]
<a href="https://youtu.be/xZuHlucXnNs">A basic schedule feature has been added.</a>Since it supports most/all commands, you should be able to do pretty much everything requested by making creative use of setplaymode, setupnext, and playme in the addschedule command. "commercialmode" has been added as well, so if you enable that mode and then schedule content to play at specific times your desire to play shows on the hour/half is now easily doable. I'll be closing this request in 72 hrs unless there a reason presents to keep it open.

**Comment by MoeFwacky** [comment]
Is there a command to view what's currently in the schedule or remove a recurring item from the schedule?

**Comment by MoeFwacky** [comment]
So I tried it out last night, but nothing kicked off, and the one time items still appear under viewschedules

Action: the simpsons;
Time: 3:30 AM
Day: saturdays

Action: commercialbreak;
Time: 3:31 AM
Day: saturdays

Action: commercialbreak;
Time: 2:35AM
Day: today

Action: commercialbreak;
Time: 2:38AM
Day: today

Action: playme seinfeld;
Time: 2:43AM
Day: today

No actions occurred with any of them. I just tried again this morning as well and got nothing. I'm not sure if I need to do anything special with the install. My update procedure was to remove all the .py files and the alias file from the folder and run the setup script to replace them. 

Also an aside, can we get 24-hour clock support for the time. I find it easier to work with, personally.

**Comment by MoeFwacky** [comment]
Another request on this, not sure if this should be a separate issue. Would it be possible to have a command that imports a list of comma separated values in as the schedule.

For example, a file would have lines like:

```
"setplaymode commercialmode",1700,everyday*
monk,1700,mondays,tuesdays,wednesdays,thursdays,fridays
"king of the hill",1730,mondays,wednesdays,fridays
"futurama",1730,tuesdays,thursdays
```

_*I don't know if everyday is a real argument, though everyday, weekdays and weekends would all be appreciated._

The script would read each line and add it to the schedule appropriately (maybe with an argument to purge and replace). It would also be great to get an export tool that writes the schedule back into the same format. I think this would make it much easier to edit a schedule for programming that runs all day (mine is set to run any time somebody is typically home and awake). 

I imagine the commands to look something like (with -r being the argument for "replace if conflict")

```
addtoschedule -r file.txt
replaceschedule file.txt
exportschedule file.txt
```

**Comment by amazingr4b** [comment]
I'm going to try and hit them in order, let me know if i missed something:

Sounds like your cron job is not triggering the tbn_schedule.py script. I'd first check your syslog/cronlog to confirm that is being launched every minute. If it is not you'll need to check and probably fix formatting on the entry in your /etc/crontab. I haven't had a chance to give the updates to add_to_cron for that a good test.

See my clarification note above regarding "playme." That should not be included. 
  
To have something happen daily specify "everyday". If you want it to repeat on a given day of the week, specify that day, like "saturday", and it will repeat every saturday at the given time.  

The weekend/weekday specification will come in a future update once I get down to it in my list. It was already on my todos for this.  

The pending update has changes to allow someone to use 24 hr time, as well as now+x(h/m), where x is a number of either hours(h) or minutes(m). examples: now+5m for 5 minutes from now. Whichever is used will be converted to the 12hr formatting it currently looks for.  

Import/export schedules will also be part of a future import and will function similar to how the tvcounts one currently does.

**Comment by MoeFwacky** [comment]
Ah, that explains it. I split &-separated entries into separate lines and gave the pi a reboot and it looks like it's working now. Is there any way to purge these old entries, or will they just run tomorrow and fall off? 

Is there any time syntax for doing something hourly at say 18 minutes after the hour? If, for example, I wanted to schedule commercial breaks to happen at regular intervals.

**Comment by MoeFwacky** [comment]
Another small issue on this (don't know if you want these reports in separate tickets or not). Looks like I can't add a show with a ! in the title

```
pi@BAD-HORSE ~ $ addschedule "freakazoid!" "10:00 AM" sundays
-bash: !": event not found
```

**Comment by MoeFwacky** [comment]
Correction on it working. It looks like anything scheduled for "today" works, but anything scheduled for "sundays" does not. 

So this entry plays:
```
star trek;
1:05 PM
today
```

And this one doesn't:
```
Action: Star Trek;
Time: 1:00 PM
Day: sundays
```

**Comment by amazingr4b** [comment]
you can clear all schedules using "python system.py clearschedules". There is not currently an alias for that. I didn't want someone to accidently use it. 

There is not currently an easy way to have something repeat at some interval shorter than daily at time x. I might add something like that, though TBH, that would have to be more than the occasional one off instance. Things like your commercial request are probably better suited for cron since it already has the /x option. 

The ! error you are getting for that show is a shell issue. Not sure how you'd get around it, so you'll probably want to google it. In the past you could have left it off and the title checker mechanism would have still found the correct title. For now its back to only supporting exact titles. Updating that mechanism to work again with the recent changes is still on my todo list. 

The following day options are currently supported:
MM/DD/YY where MM is the month, DD is the Day, and MM is year. - repeating
monday - repeating
tuesday - repeating
wednesday - repeating
thursday - repeating
friday - repeating
saturday - repeating
sunday - repeating
weekends - repeating
weekdays - repeating
today - one time event, automatically removed at 11:59PM(when not broken. looks like its currently broken)  

I'll likely be adding a way to specify repeating vs single time events. 

The following time options are currently supported:
24hr time - HH:MM
12hr time - HH: MM AM/PM
now+Xm/h - now+5m OR now+2h (Now + x minutes/hours.)

For supported actions, anything that does not require input beyond submission is supported. Additionally, "wait" is also supported. Wait can be used to specify wait x seconds. Used when you have multiple actions schedules for the same time/day.

**Comment by MoeFwacky** [comment]
So it was working for a good chunk of the afternoon, but then suddenly stopped. I tried restarting the schedule script and rebooted the pi once or twice to try and get it to kick back in, but it's not kicking on it's own. Even the things I scheduled for "today" have stopped working. Here's the output from my cronlog

```
Nov 20 18:41:17 BAD-HORSE /usr/sbin/cron[2036]: (CRON) INFO (pidfile fd = 3)
Nov 20 18:41:17 BAD-HORSE /usr/sbin/cron[2039]: (CRON) STARTUP (fork ok)
Nov 20 18:41:17 BAD-HORSE /usr/sbin/cron[2039]: (*system*) ERROR (Missing newline before EOF, this crontab file will be$
Nov 20 18:41:17 BAD-HORSE /usr/sbin/cron[2039]: (CRON) INFO (Running @reboot jobs)
Nov 20 18:41:17 BAD-HORSE /USR/SBIN/CRON[2044]: (root) CMD (python /home/pi/hasystem/piplaystate.py &)
Nov 20 19:09:01 BAD-HORSE /USR/SBIN/CRON[2299]: (root) CMD (  [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/se$
```

and these are the scheduled items that should have kicked off (I added the second two after the first failed to kick off)

```
Action: arrested development;
Time: 6:30 PM
Day: sunday

Action: arrested development;
Time: 6:35 PM
Day: today

Action: arrested development;
Time: 6:40 PM
Day: today
```

and these are the entries in /etc/crontab
```
@reboot pi python /home/pi/hasystem/piplaystate.py
@reboot pi python /home/pi/hasystem/piplaystate.py > /dev/null 2>&1
* * * * * pi python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1
@reboot pi python /home/pi/hasystem/piplaystate.py > /dev/null 2>&1 &
```

**Comment by amazingr4b** [comment]
I'd remove the first and second entries, and " &" to the end of the 3rd, and then add a new line at the very end like the error message says is missing.

**Comment by MoeFwacky** [comment]
That did the job. Thanks.

**Comment by MoeFwacky** [comment]
The viewschedules readout is difficult to parse, and at the number of items i have, it runs clear off the page. It would be great if we could get a better readout for that, or even better a readout in the webUI broke down by days.

**Comment by amazingr4b** [comment]
The schedule stuff is still a work in progress. That command temporarily shows everything because I haven't started actually working on it yet. A future version will have ways to search/filter the output once I have other schedule related stuff finished.

**Comment by amazingr4b** [comment]
I'm closing this case. Among other things, additional filter options have been added to viewschedules, <a href="https://youtu.be/oG37mxF5ATs"> seen here.</a> Any bugs/new features related to this can be requested as a new case. There are no plans to update/maintain the UI files, so don't open anything related to that.
