### ISSUE TITLE
Commercial Mode - "Error Creating Play Queue"

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#28]
To start, the commercial mode is working fine, but commonly when it kicks off a commercial I'll get an "Error Creating Play Queue" error on the rasplex. The unfortunate nature of this error, is that it's a giant dialogue box in the center of the screen, which I need to use a keyboard to dismiss. I know I've seen this one before, but I don't remember how it was resolved.

**Comment by amazingr4b** [comment]
Every once in a while that error will happen. A recent plex update has a bug causing that to error to occur frequently. The update they posted a couple days ago seems to have fixed it, as I haven't seen the error since updating to it. ... I added "hitok" a while a go for the random one off instances to dismiss the message without needing a keyboard connected to the pi.
