### ISSUE TITLE
Output error: wrong text string

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#3]
A minor thing, but while I'm posting bugs, why not. 

When adding shows to a block, the output text prints the block name instead of the expected show name (see below)

```
Enter New Block Name

Name: blockname
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:seinfeld
blockname has been added to the block.
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:the simpsons
blockname has been added to the block.
```

Expected behavior is like something below:

`<TV Show> has been added to the block.`
`<TV Show> has been added to the <Name of Block> block.`
Successfully added <TV Show> to the block

**Comment by amazingr4b** [comment]
This is a known bug that has existed since the feature was first added. I haven't got around to fixing the output yet. At some point I will, so I'll leave this case open until then.

**Comment by amazingr4b** [comment]
This is fixed in the next release:  

Command line options not present. Proceeding to query mode.
Enter New Block Name

Name: Test1
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:Psych
Psych has been added to the block.
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
