### ISSUE TITLE
Scheduled Items Not Playing

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#30]
Troubleshooting/Bug Issue: Scheduled Items not playing

1- What Happened: 
Scheduled item did not play
1a- What you expected to happen: 
Scheduled item to play

2- TBN-Plex Version:
3.05exp

3- Command entered:
`addschedule "adventure time" 21:40 today`

4- Error Message/Output:
`Successfully added item to schedule.`

and in viewschedules
```
Action: adventure time;
Time: 9:40 PM
Day: today
```

5- If schdule/automation, what happened when you manually tried the action/ran the schedule script at a scheduled time? Provide the output here:
When running the scheduled script a the scheduled time
```
pi@BAD-HORSE ~/hasystem $ python tbn_schedule.py
adventure time;
today
Executing: python /home/pi/hasystem/system.py adventure time
ERROR: adventure NOT FOUND.
```

If I try to play the item manually it works
```
pi@BAD-HORSE ~/hasystem $ playme "adventure time"
Trying to start: Adventure Time

Playing Business Time From the show Adventure Time Now, Sir

```

6- If applicable, does the media item exist in your library, and how is the name formatted in your Plex Web?
Media exists as "Adventure Time" in the library

7- If cron related, what do your TBN-Plex cron entries look like?
crontab:
```
* * * * * pi python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &
@reboot pi python /home/pi/hasystem/piplaystate.py > /dev/null 2>&1 &
```

cronlog:
```
Dec  1 21:40:01 BAD-HORSE /USR/SBIN/CRON[8996]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:41:01 BAD-HORSE /USR/SBIN/CRON[9018]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:42:01 BAD-HORSE /USR/SBIN/CRON[9021]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:43:01 BAD-HORSE /USR/SBIN/CRON[9025]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:44:01 BAD-HORSE /USR/SBIN/CRON[9032]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:45:01 BAD-HORSE /USR/SBIN/CRON[9037]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:46:01 BAD-HORSE /USR/SBIN/CRON[9057]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:47:02 BAD-HORSE /USR/SBIN/CRON[9067]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Dec  1 21:48:01 BAD-HORSE /USR/SBIN/CRON[9070]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
```

**Comment by amazingr4b** [comment]
In the original version of the schedule script your example would have worked. Unfortunately there were a bunch of issues with other scheduled actions because of how that worked. Due to those bugs the way the commands generated were built was changed. The last schedule script update had fixes for all those bugs. 

The problem you are having has to do with how the schedule generated command is being executed:

Executing: python /home/pi/hasystem/system.py adventure time
ERROR: adventure NOT FOUND.


When the schedule script finds a time/date match it reads in the action, builds a command, and then executes it via the system library and execute command. When you have a title or command with a space(" ") in it, and that item is not wrapped in quotes, your computer treats each word as a separate argument rather than a single item. For now you have to add escaped quotes around items with spaces. 

To use your adventure time example as an example, you'd format the entry as follows:

addschedule "\"adventure time\"" 21:40 today

This one is getting closed on sunday unless some other related issue is reported.

**Comment by MoeFwacky** [comment]
It's not taking them at all in that format. It's now assuming the second word is supposed to be the time.

```
pi@BAD-HORSE ~ $ python /home/pi/hasystem/system.py addschedule ""adventure time"" 15:00 sunday
Traceback (most recent call last):
  File "/home/pi/hasystem/system.py", line 7371, in <module>
    time = timechecker(time)
  File "/home/pi/hasystem/system.py", line 7297, in timechecker
    d = datetime.strptime(thing, "%H:%M")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'time' does not match format '%H:%M'
```

**Comment by amazingr4b** [comment]
Apparently gethub doesn't like \\. Updated my previous comment to show the slash to escape the ". I'm working on something to automatically add them for shows/movies, but it might not be in an update for a few days.

**Comment by MoeFwacky** [comment]
I re-entered the schedule with the syntax you provided. When running the tbn_schedule.py script at the appropriate time, I got the following readout and nothing played.

```
pi@BAD-HORSE ~/hasystem $ python tbn_schedule.py
"adventure time";
monday
"metalocalypse";
tuesday
"the drinky crow show";
wednesday
"harvey birdman, attorney at law";
thursday
"saul of the mole men";
friday
"archer (2009)";
saturday
```

I did it again this morning and got the following  (this is the only item scheduled to play at this time on any day.
```
pi@BAD-HORSE ~/hasystem $ python tbn_schedule.py
"pinky and the brain";
weekends
pi@BAD-HORSE ~/hasystem $ playme "pinky and the brain"
Trying to start: Pinky and the Brain
```

The readout in the schedule looks proper, so i'm not sure the issue.
```
Action: "pinky and the brain";
Time: 9:30 AM
Day: weekends
```

**Comment by amazingr4b** [comment]
I've tested that using the schedule script that is posted, and I cannot duplicate the problem: 

pi@raspberrypi:~/hasystem $ date
Sat  3 Dec 14:40:18 CST 2016
pi@raspberrypi:~/hasystem $ python tbn_schedule.py                        
 "Pinky and the Brain";
saturday
Executing: python /home/pi/hasystem/system.py "Pinky and the Brain"
Trying to start: Pinky and the Brain

Playing Brainstem From the show Pinky and the Brain Now, Sir
pi@raspberrypi:~/hasystem $ nowplaying
Now Playing: Pinky and the Brain
Episode: Brainstem
pi@raspberrypi:~/hasystem $ date
Sat  3 Dec 14:41:00 CST 2016
pi@raspberrypi:~/hasystem $ viewschedules -a "Pinky and the Brain"
The following items were found for action Pinky and the Brain:

Action: "Pinky and the Brain";
Time: 2:40 PM
Day: weekends


Done.

pi@raspberrypi:~/hasystem $ sudo date -s "3 DEC 2016 08:00:00"
Sat  3 Dec 08:00:00 CST 2016
pi@raspberrypi:~/hasystem $ date
Sat  3 Dec 08:00:02 CST 2016
pi@raspberrypi:~/hasystem $ addschedule "Pinky and the Brain" 08:00 weekends
Pass: Media
Successfully added item to schedule.
pi@raspberrypi:~/hasystem $ date
Sat  3 Dec 08:00:31 CST 2016
pi@raspberrypi:~/hasystem $ python tbn_schedule.py
"Pinky and the Brain";
saturday
Executing: python /home/pi/hasystem/system.py "Pinky and the Brain"
Trying to start: Pinky and the Brain

Playing Pinky & The Fog From the show Pinky and the Brain Now, Sir

...

I'm using the schedule script that is posted on gethub for those tests, though I am testing a version of the system script that is automatically escaping the title, which is why I'm not If you check the output you'll see what mine and yours are outputting for title is the same. I do notice that in your output when you ran the tbn_schedule script your output said "weekends" instead of "saturday." Is your system time/date correct? As is I'm not finding any problems with the schedule script that would case your problem.

**Comment by MoeFwacky** [comment]
I checked my date and the readout is correct
`Sat Dec  3 15:47:09 PST 2016`

I tried it out with saturday instead of weekends and it seemed to work okay. So maybe it's an issue with the weekends, weekdays and everyday arguments?

**Comment by amazingr4b** [comment]
I tested all those options before I posted my last comment and had no problems. You can try using the clearschedules action and setting things up again. Other than than that you can join the discord channel to get real time feed back while you do some troubleshooting of your setup. As is, without an error message, or output from the scripts indicative of an error there is nothing further I'm going to be able to do.

**Comment by MoeFwacky** [comment]
I'll pop into discord in a bit. But for now, here's the readout when I run tbn_schedule.py at 10:30 PM on Saturday. This was after I purged the schedules table, and reinstalled the scripts with the most current system_setup.py and re-entered the schedules

```
pi@BAD-HORSE ~/hasystem $ python tbn_schedule.py
"stargate sg-1";
sunday
"stargate sg-1";
monday
"stargate atlantis";
tuesday
"stargate universe";
wednesday
"rick and morty";
thursday
"quantum leap";
friday
```

**Comment by amazingr4b** [comment]
Discussed in discord. New version posted that makes it easier to add title items as schedules, with checks to verify commands/titles. Closing this case. If something new pops up a new issue can be opened.
