### ISSUE TITLE
Feature Request - Replace Show in Block with New Show at End of Series

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#9]
I've been running the script on a schedule for a while now with a mix of long-running and short-running shows. I'd like a feature that replaces a show in a block with a another show instead of looping back around to the beginning. Sort of a horizontal queue, if the block is considered a vertical queue.

Example:
sample_block
Show 1
Show 2 --> Show 2a --> Show 2b --> Show 2c
Show 3

So when the last episode in the database for Show 2 plays, Show 2a replaces it in the block, and soon until it gets to the end of the defined shows and loops back around. I don't know how, particularly, this would work in situations (such as in my system) where shows appear in multiple blocks or multiple times in a block.

Also, I don't know how feasible this actually is without having to completely rewrite the block system.

**Comment by amazingr4b** [comment]
This isn't likely to be added. There is an action in the current version you can use 'replaceinblock blockname newitem olditem' that will replace one item in a block with a new item.

**Comment by MoeFwacky** [comment]
Understandable. On a side note, what are the limits on feature requests? I have a handful of suggestions floating around in my head, and while I can safely assume that a web GUI is out of scope, I'm not entirely sure where to draw the line.

**Comment by amazingr4b** [comment]
You can submit them. Things that will or wont be done will be marked as such.

**Comment by amazingr4b** [comment]
Turns out this one is being added. I've thought about it one more, and I think it is inline with the idea behind the scripts purpose.

**Comment by amazingr4b** [comment]
Here's how it currently works for the testing that will be posted tomorrow once I finish the initial tests:
you specify a show(to be replaced), a new show, a block, and a playflag. When the shows playcount resets it will check it against the shows to be replaced, and if it is found the old show will be replaced by the new one. Multiple new shows will be allowed, and they will be removed as they are played through. Currently it will only support replacing shows for a single block, though that may change. The playflag is a on/off necessary flag. The playflag should be set to "yes" except in this case where you are adding a previously unwatched show(not in the TVCounts table) to a block and marking it for replacement. In this case and only in this case should the playflag should be set to "no," otherwise the show will be replaced the first time it is played due to how the the various checks behind the scenes work. 

Of note is the replacement will occur even when the show plays independent of a block. This is intentional.

**Comment by amazingr4b** [comment]
I'm closing this one since this has been added. If you'd like to see any changes to it in the future open a enhancement case. If you find a bug feel free to open a case for that.
